### ISSUE TITLE
No outgoing transition from parallel state SCXML

### ISSUE THREAD

**Issue by ConcurrentState** [sverweij/state-machine-cat#104]
### Expected Behavior

When rendering a SCXML with an outgoing transition from a parallel state it is rendered like from a compound state.

### Current Behavior

The transition gets lost and is not rendered.

In this scxml

### Steps to Reproduce (for bugs)

1. 
```` xml
<?xml version="1.0" encoding="UTF-8"?>
<scxml version="1.0" initial="Start">
    <state id="Start">
        <transition event="_FORK" target="ParallelState"/>
    </state>
    <!-- change PrallelState from "parallel" to "state",
         then it renders as expected -->
    <parallel id="ParallelState">
        <transition target="Done"/>
        <state id="Region1">
        <initial>
            <transition target="State1"/>
        </initial>
            <state id="State1">
                <transition event="_DONE1" target="Final_1"/>
            </state>
            <final id="Final_1"/>
        </state>
        <state id="Region2">
            <initial>
                <transition target="State2"/>
            </initial>
            <state id="State2">
                <transition event="_DONE2" target="Final_2"/>
            </state>
            <final id="Final_2"/>
        </state>
    </parallel>
    <state id="Done">
      <transition event="_END" target="Final_3"/>
    </state>
    <final id="Final_3"/>
</scxml>
````

2.

![not_ok](https://user-images.githubusercontent.com/60062047/72680625-56a2e480-3abc-11ea-9822-c72ba4904703.png)

3.
![ok](https://user-images.githubusercontent.com/60062047/72680630-65899700-3abc-11ea-8fd0-72d4f450e202.png)

4.
Change PrallelState from "parallel" to "state",  then it renders as expected.

It could be just the import of the SCXML, because here
[stama-visualiser](https://github.com/Hades32/stama-visualizer)
there is an outgoing transition from a parallel state in the example diagram.

Thanks for having a look, b.t.w. awsome tool!

### Your Environment

* Version used: lastest for Atom
* Node version: 8.12
* Operating System and version: Win 7 64

**Comment by sverweij** [comment]
Hi @ConcurrentState - thanks for raising this issue. 

It's definitely unexpected behaviour in need of a fix. Somewhere the fact that parallel states are 'just' a compound-state-with-benefits gets lost in translation.

**Comment by ConcurrentState** [comment]
Glad to help.

````
 initial,
Start,
Done,
ParallelState [type=parallel ] {
    Region1 {
        Region1.initial,
        State1,
        Final_1 [type=final ];
        
        Region1.initial => State1;
        State1 => Final_1: _DONE1;
    },
    Region2 {
        Region2.initial,
        State2,
        Final_2 [type=final ];
        
        Region2.initial => State2;
        State2 => Final_2: _DONE2;
    };
    
},
Final_3 [type=final ];

initial => Start;
Start => ParallelState: _FORK; 

# this transition gets lost when
# converting from scxml to smcat with
# >smcat -T scxml -I smcat aFILE.scxml
ParallelState => Done: _DONE; 
Done => Final_3: _END;
````

This works as expected, its probably the SCXML import.
![smcat_ok](https://user-images.githubusercontent.com/60062047/72681153-15f99a00-3ac1-11ea-8cf0-517a537cca00.png)

I did not check with the json format, which is also of interest to me.

**Comment by sverweij** [comment]
Found the root cause in the  [scxml parse code](https://github.com/sverweij/state-machine-cat/blob/develop/src/parse/scxml/index.js#L143) - this needs to have a `.concat(extractTransitions(lMachine.parallel))` added to it. I'll be releasing a new version of state-machine-cat today that includes the fix.

**Comment by ConcurrentState** [comment]
Thanks for this super fast reaction.

I did a roundtrip from par.smcat (which renders ok) to .json and then to .svg
>smcat -T json -I smcat par.smcat
>smcat -T svg -I json par.json

The outgoing transituin from the parallel state is lost again.
So it is probably not only the scxml parse code affected...

**Comment by sverweij** [comment]
Thanks! I'll check that one as well. 

In the mean time: the fix is up on the beta test site - https://sverweij.gitlab.io/state-machine-cat/

If you set the input type to SCXML and drop your reproduction sample into it you should see it works correctly

<img width="1332" alt="image" src="https://user-images.githubusercontent.com/4822597/72681615-9e7a3980-3ac5-11ea-952d-c798094c6160.png">

**Comment by sverweij** [comment]
Also published to npm as `state-machine-cat@6.0.1-beta-1` just now.

**Comment by sverweij** [comment]
Hi @ConcurrentState I've tried to reproduce the scenario you described (take the smcat source you put in the issue, transform it to json with the command line and then transform the json to svg) - but wasn't able to reproduce the issue.

**Comment by ConcurrentState** [comment]
> 
> 
> Hi @ConcurrentState I've tried to reproduce the scenario you described (take the smcat source you put in the issue, transform it to json with the command line and then transform the json to svg) - but wasn't able to reproduce the issue.

I rechecked and you are right, probably confused the file names... apoplgies.

**Comment by sverweij** [comment]
NP @ConcurrentState - I'll merge the PR and release it as a regular version (and update atom-state-machine-cat-preview shortly after).
