### ISSUE TITLE
How to update smcat svg image in a webpage

### ISSUE THREAD

**Issue by marcoavnet** [sverweij/state-machine-cat#108]
Hello,
currently I am using your project to visualize a state machine in a web-page using this code based on the inpage.html example:

```
<script type="text/x-smcat" src="state_diagram.smcat" data-dot-graph-attrs="splines=ortho"></script>
```
The file state_diagram.smcat is auto generated every second by an external application. The SVG image needs to be regenerated. What is the best way using your library?

Thanks
Marco

**Comment by sverweij** [comment]
hi @marcoavnet - the state-machine-cat library renders static diagrams. 

The 'in page' script example you currently use renders the diagrams only once - on page load.

If you want to update the picture in-place (so you e.g. get a nice animation, or you have the diagram update while you change the source) you can do so by re-rendering the diagram at the moment you want it to. The [on line interpreter](https://state-machine-cat.js.org) takes this approach for instance. There's a lot of ways to achieve this. 

If you are tied to your current setup you could for instance have a script in the page poll for the file at an interval (although I'm sure there's more elegant solutions out there using websockets). E.g. 

> rerender.js
```javascript
import { render } from "state-machine-cat";

function rerender(pUrl) {
  fetch(pUrl)
    .then(pResponse => {
      return pResponse.text();
    })
    .then(pText => {
      console.log(pText);
      document.getElementById("moving-picture").innerHTML = render(pText, {
        inputType: "smcat",
        outputType: "svg",
        direction: "top-down",
        engine: "dot",
        desugar: false,
        dotGraphAttrs: [{ name: "bgcolor", value: "transparent" }]
      });
    })
    .catch(pError => console.error(pError));
  window.setTimeout(() => rerender(pUrl), 1000); // re-call every 1000 ms
}

rerender("state_diagram.smcat");

```

> rerender.html
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <script src="dist/rerender.bundle.js" defer></script>
  </head>
  <body>
  <div id="moving-picture"></div>
  </body>
</html>
```

(and to get the web usable bundle use webpack with this config):
> webpack.config.js
```javascript
module.exports = () => {
  return {
    entry: "./rerender.js",
    mode: "development",
    output: {
      filename: `rerender.bundle.js`
    }
  };
};
```

> An even cruder way to do this is to keep using the 'in page' script approach, but to have the 
> _entire_ page reload at an interval with the refresh meta tag
> (`<meta http-equiv="refresh" content="1">` in the header)

HTH

**Comment by marcoavnet** [comment]
Thank you for your suggestions.
This looks promising.
I am a bit confused how it all goes together.

I placed your whole git repo here (apache webserver):
http://xlnx-fae-srv-ldap.westeurope.cloudapp.azure.com/state-machine-cat

The files rerender.js, rerender.html and webpack.config.js are in the state-machine-cat root dir.

http://xlnx-fae-srv-ldap.westeurope.cloudapp.azure.com/state-machine-cat/rerender.html
Doesn't work due to the different script location path.

So I need to generate this dist/rerender.bundle.js file using npm and webpack?
I tried this:

```
root@myhttpd_test:/var/www/html/state-machine-cat# npx webpack --config webpack.config.js
Hash: 6e2289fc59a8bff6f5e9
Version: webpack 4.41.5
Time: 132ms
Built at: 03/03/2020 5:18:29 PM
             Asset      Size  Chunks             Chunk Names
rerender.bundle.js  4.75 KiB    main  [emitted]  main
Entrypoint main = rerender.bundle.js
[./rerender.js] 643 bytes {main} [built]

ERROR in ./rerender.js
Module not found: Error: Can't resolve 'state-machine-cat' in '/var/www/html/state-machine-cat'
 @ ./rerender.js 1:0-43 10:60-66
```

**Comment by sverweij** [comment]
hi @marcoavnet you indeed need to create a bundle from the various javascript sources with a bundler as (I've used webpack as I'm familiar with that). 

I was assuming you already had a project going. You don't need to clone the state-machine-cat repo. Just create a new folder and in there create an npm project, and install state-machine-cat and the webpack command line:

```sh
# create a manifest file ('package.json') with defaults
npm init --yes

# install state-machine-cat ...
npm install state-machine-cat 

# ...  and the webpack and the webpack cli as a development dependency
npm install --save-dev webpack webpack-cli
```
copy `rerender.html`, `rerender.js`, `webpack.config.js` here and create a  `state_diagram.smcat`

web packing should now work:

```sh
# create the bundle with webpack
npx webpack
```

After this the bundle will be available in the `dist` folder

You can now serve the folder on a web server and navigate to `rerender.html`, which should rerender the contents of `state_diagram.smcat` every second.

> You can also download [state-machine-cat-issue-108.zip](https://github.com/sverweij/state-machine-cat/files/4289735/state-machine-cat-issue-108.zip), unzip it, and run
> ```sh
> npm install
> npx webpack
> ```

HTH

> P.S. As I said in the first comment , there's a lot of ways to re-render a state chart (or any
> picture for that matter) in place. This is just an example I know works - but it might not be
> the best solution for your situation, nor is the mechanism (polling) a best practice...

**Comment by marcoavnet** [comment]
Thank you very much. It is really nice that you packed everything up.
It works as expected:
http://embedded-world.hoefle.co/state-machine-cat-issue-108/rerender.html

This will be for a VPN state-machine visualization were we show StrongSwan with TPM support.
I'll send you a link once it is finished.
I will now close the issue.

Best regards
Marco
