### ISSUE TITLE
History child of parallel state not rendering correctly

### ISSUE THREAD

**Issue by joeriexelmans** [sverweij/state-machine-cat#112]
### Expected Behavior
In the following state machine:
```
initial,
outer,
parallel {
  s1 {
    s11 -> s12;
  },
  s2 {
    s21 -> s22;
  },
  history;
};

initial -> parallel;
parallel -> outer;
outer -> history;
```

The history state is expected to show up as a child of the parallel state...
### Current Behavior
Instead, the history state is rendered incorrectly and shows up next to the parallel state:
![image](https://user-images.githubusercontent.com/37209254/75770823-079dcf80-5d49-11ea-9e73-90dd06a6256d.png)

If the history state is not mentioned in any transition, it is not rendered at all.

### Steps to Reproduce (for bugs)
Whenever a parallel state has a history child, the problem occurs.

### Context
For my purposes, history states should be allowed to be children of parallel states.

### Your Environment
Ubuntu 19.10.
state-machine-cat 6.0.1 from NPM.
Node 10.15.2 (from Ubuntu repository)

Exact same problem with the online version: https://state-machine-cat.js.org/

**Comment by sverweij** [comment]
hi @joeriexelmans thanks for raising this issue - it seems you've bumped into a bug. I've reproduced it and have found a likely root cause. I hope to fix it over the coming days - I'll keep you posted in this thread.

**Comment by sverweij** [comment]
@joeriexelmans Found a fix quicker than anticipated - I've put it up on https://sverweij.gitlab.io/state-machine-cat/ and published it on npm with the beta tag (`state-machine-cat@v6.0.4-beta-1`). 

=> Could you verify if it works for your original use case as well?

I'll publish to the regular npm/ state-machine-cat.js.org and the atom package later this week.

B.t.w. Thanks for your excellent bug description - it helped a lot in narrowing down the fix. Your example now renders like this:

![state-machine-2020-03-03T19_34_13 507Z](https://user-images.githubusercontent.com/4822597/75812377-6b96b700-5d8e-11ea-8c64-88852d2d9f3b.png)

**Comment by joeriexelmans** [comment]
Hi @sverweij ! Thank you very much for the quick response.
I can confirm your fix is working for my original use case.

**Comment by sverweij** [comment]
hi @joeriexelmans thanks for testing & getting back! I've published version 6.0.4 to npm and state-machine-cat.js.org (the atom package will follow later)

**Comment by joeriexelmans** [comment]
@sverweij By the way, if you are interested in a bunch of statecharts that I rendered, you can have a look at this directory of this branch of this repository:
https://msdl.uantwerpen.be/git/simon/SCCD/src/joeri/test/test_files
Most images look pretty OK. They will look better when Graphviz' dot starts natively supporting true edges between clusters :)

The project I'm working on is my master thesis: A statechart interpreter with configurable semantic variability (see http://msdl.cs.mcgill.ca/people/joeri/10_Thesis). The input format is based on SCXML, but differs in some ways. To render statecharts, the input format is loaded to an internal state tree representation (which serves as input to the interpreter), and this tree is then converted to your 'smcat' format in a dirty script.

**Comment by sverweij** [comment]
@joeriexelmans o wow that looks like _cool_ master thesis. Thanks for sharing this!

[render.py](https://msdl.uantwerpen.be/git/simon/SCCD/src/joeri/test/render.py) is the conversion script?

I'm still looking for an alternative to GraphViz that has the capabilities needed for state machines, but that look better (so _pretty OK_ gets to _wow that's nice!_) and have better native web support.
