### ISSUE TITLE
Abnormalities while rendering internal transitions to nested states

### ISSUE THREAD

**Issue by LeeDoty** [sverweij/state-machine-cat#117]
### Expected Behavior
Transition lines should originate on the edge of the "from state" (i.e. the outer state)

A couple of small, unrelated things (related to the example below) to notice.  Not sure if these are fixable, but I thought it would be helpful to let you know:

* Lines unnecessarily cross:
    * examples: 3. ee and 6. ff, 1. cc and 9. dd
    * would be neat if transitions from W to T could go directly to the left of T (to not cross unnecessarily with the internal transitions.

### Current Behavior
transitions from Y to substates originate in empty space inside Y
(bonus: and they cross too often)

### Possible Solution
IMHO, it would be neat if:
 * the internal transitions from Y to substates could come from the right side (or bottom) and from the edge of Y's bounding line.
 * the transition lines could cross only when necessary

### Steps to Reproduce (for bugs)
Here is a model displaying the issue:
X [label="X" color="black"] :
{
    X.Y [label="Y" color="gray"] :
    {
        X.Y.V [label="V" color="gray"] :
        {
            X.Y.V => X.Y.Z : 1. Done;
        },
        X.Y.Z [label="Z" color="gray"] : ,
        X.Y.T [label="T" color="gray"] :
        {
            X.Y.T => X.Y.V : 3. bb;
            X.Y.T => X.Y.V : 4. bb;
            X.Y.T => X.U : 2. jj;
            X.Y.T => X.W : 1. Done;
        };
        X.Y => X.Y.T : 2. aa;
        X.Y => X.Y.T : 1. cc;
        X.Y => X.Y.T : 9. dd;
        X.Y => X.Y.T : 3. ee;
        X.Y => X.Y.T : 6. ff;
        X.Y => X.Y.T : 4. gg;
        X.Y => X.Y.T : 8. hh;
        X.Y => X.Y.T : 7. ii;
        X.Y => X.Y.T : 5. ll;
    },
    X.W [label="W" active color="red"] :
    {
        X.W => X.Y.T : 2. aa;
        X.W => X.Y.V : 8. dd;
        X.W => X.U : 4. jj;
        X.W => X.Y.V : 1. kk;
        X.W => X.Y.V : 5. ff;
        X.W => X.Y.T : 3. gg;
        X.W => X.Y.V : 7. hh;
        X.W => X.Y.V : 6. ii;
    },
    X.U [label="U" color="gray"] : ;
    X.initial => X.W;
};

### Context
I'm pushing to use smcat in a production monitoring system.  We have some fairly intense diagrams (the sample above is an obfuscated example) and the main selling point will be that the graphs are much clearer than the representation we currently use.

I absolutely love smcat.  I very much appreciate that you made it available and that you've been so responsive to my requests so far.  

Love your work!!

### Your Environment
Version used: state-machine-cat-preview 4.6.10 in atom 1.45.0 x86 on mac
also in https://state-machine-cat.js.org/  v6.0.5

**Comment by sverweij** [comment]
hi @LeeDoty 

state-machine-cat is bumping into the limits of the algorithms of the render engine (GraphViz) it's using. There _is_ a little that can be squeezed out of GraphViz (e.g. possibly by  - like your suggestion in #118 - to expose more of the underlying render model upwards), but not enough to make renditions perfect. 

I'm looking into other options that I hope have different trade-offs that turn out better for state-machine-cat's use (also see my response on #116). 

(Not on the short term, though - there's some AfK stuff I need to take care of...)
