### ISSUE TITLE
Dual License

### ISSUE THREAD

**Issue by jdrew1303** [sverweij/state-machine-cat#12]
Currently the license is GPL. This is fine for the majority of cases where the average user will generate the SCXML files and use them statically. If you want to use the library programmatically then its next to impossible to use under the current licensing. It's possible to use it server side in SaaS products without any hassle but using it in the frontend causes a world of pain. Trying to get a derivative with strong separation to stop the license affecting the entire codebase is next to impossible on the frontend. This stops most companies I work with from allowing its use, which is a shame because it's a great library.

### Possible Solution
If its possible to dual license it with the BSD or preferably MIT license then that would solve the issue.

### Context
I work with enterprise software (ERP, Banking, reporting, etc). Most have an outright ban on using GPL'd libraries in case it could open them up to litigation.

**Comment by sverweij** [comment]
I chose GPLv3 deliberately at the time, over MIT/ BSD/ Apache. I need some time to re-evaluate if GPLv3 is still aligned with why I put time in maintaining state-machine-cat.

**Comment by sverweij** [comment]
From the next version on state-machine-cat will be MIT licensed (see f60be0c)

At this time the MIT license fits better with the purpose I have in mind with it - which is different then it was in 2016. @jdrew1303 thanks for bringing this to my attention and having me re-evaluate.

**Comment by sverweij** [comment]
just updated the `master` branch, released 2.6.6 on npm  and the online interpreter on state-machine-cat.js.org (and https://sverweij.gitlab.io/state-machine-cat) - all with the license updated.
