### ISSUE TITLE
Escaped double quotes are displayed as escaped

### ISSUE THREAD

**Issue by hefroy** [sverweij/state-machine-cat#121]
It's necessary to escape double quotes when they are contained in actions (or state names). However the escaping is currently being rendered rather than un-escaped.

### Expected Behavior
The escaped double quotes are changed to double quotes.

### Current Behavior
The escaped double quotes are displayed as escaped double quotes.

### Possible Solution
The escaping should be stripped.

### Steps to Reproduce
```
a -> b : "/call_function_with_string(\"a string\");";
```

### Context
It's possible the action is calling a function with a string argument.

### Your Environment
https://state-machine-cat.js.org/
Version: 7.0.2

**Comment by sverweij** [comment]
@hefroy thanks for finding & reporting this! Fix is on its way.

**Comment by sverweij** [comment]
@hefroy I've deployed a new version on live (https://state-machine-cat.js.org) in which this issue is fixed - npm will follow suit in about 5 minutes. 

=> Could you let me know in case this doesn't solve your issue?

**Comment by hefroy** [comment]
Hi @sverweij, thanks for the very fast response! Glad to help out, I really like what you've done here.
Yep, your fix looks good to me!

**Comment by hefroy** [comment]
One last thought about this one: do you think it's worth mandating that the escape character '\' is also escaped? About the only reason to do would be for when you have a '\' character at the end of you action string, which will probably never be the case, apart from a weird comment such as:
```
a -> b : "my_action(); // Here's a bat emoji /|\ ^._.^ /|\";
```
But it probably isn't worth making users do this for such a slim use-case. What do you think?
