### ISSUE TITLE
Sometimes transition text is strangely placed

### ISSUE THREAD

**Issue by hefroy** [sverweij/state-machine-cat#124]
Occasionally the text for a transition is not placed anywhere near the arrow it applies to.
Possibly related to #125.

### Expected Behavior
The transition text should be placed next to the arrow.

### Current Behavior
The transition text seems to be pulled off to one side.

### Steps to Reproduce
Sorry for the rather verbose example, but this issue seems to only occur in certain circumstances, this is one that I found (see the transition text "strangely_placed_text"):
```
root.initial,
s1,
s2 [type=parallel] {
  s3 {
    s3.initial,
    a_very_long_name_just_to_emphasize_the_issue;
  };
},
c1 [type=choice],
j1 [type=junction],
final;
root.initial -> s1;
s1 -> c1 : "ev1";
s2 -> s1 : "tm(3)";
s3.initial -> a_very_long_name_just_to_emphasize_the_issue;
c1 -> j1 : "[is_ready()]";
c1 -> s1 : "[else]";
j1 -> s2 : "";
s2 -> final : "strangely_placed_text";
```

### Context
When the transition text appears randomly in the diagram it is very unclear what it applies to, leading to confusion.

### Your Environment
https://state-machine-cat.js.org/
Version: 7.0.3

**Comment by sverweij** [comment]
Hi @hefroy sorry for the slow response.

LSS: I'm afraid I won't be able to fix this issue short term.

Below the surface state-machine-cat uses [GraphViz](https://graphviz.gitlab.io) for rendering the diagram. There's a lot tweakable in GraphViz to get the diagram nice and shiny, but  (nested) state machines bump into the limits of what is currently possible. This issue and the next you filed (#125) are samples of that - as well as are some issues filed earlier (#117, #116). 

It's one of the reasons I want to change over to a different (or at least _additional_) auto rendering engine for state-machine-cat - [ELK.js](https://github.com/kieler/elkjs) (based on the Eclipse Layout Kernel)/ [sprotty](https://github.com/eclipse/sprotty)) is looking promising in that regard.

> Also check graphviz' maintainers comment [on this post](https://news.ycombinator.com/item?id=23475225) on hacker news a few days ago.

**Comment by hefroy** [comment]
Hi @sverweij, no problem - yeah I figured that GraphViz might have been the root cause.
