### ISSUE TITLE
SVG conformance ?

### ISSUE THREAD

**Issue by Kochise** [sverweij/state-machine-cat#129]
Hi, currently writing a LaTeX package to add `smcat` support, it appears `Inkscape` (and `inkview.exe`) cannot interpret correctly the produced `svg` output, ie. from your own example :

    initial,
    doing: entry/ write unit test
           do/ write code
           exit/ ...,
    # smcat recognizes initial
    # and final states by name
    # and renders them appropriately
    final;
    
    initial      => "on backlog" : item adds most value;
    "on backlog" => doing        : working on it;
    doing        => testing      : built & unit tested;
    testing      => "on backlog" : test not ok;
    testing      => final        : test ok;
    
The `svg` output "features" something like `<polygon fill="transparent" stroke="transparent" ...` where `"transparent"` is not recognized.

Check this out :

https://tools.ietf.org/html/draft-brownlee-svg-rfc-13 <- https://tools.ietf.org/id/svg

Did you meant `stroke-opacity` instead of `stroke` ?

Please check the result not just in web browsers, but also with more conformant and less forgiving tools.

Btw you're not the only one to produce "strange" `svg` files, https://github.com/mermaid-js/mermaid is also pretty "lazy" regarding `svg` conformance and `Inkscape` compatibility...

Anyway, good job overall...

**Comment by sverweij** [comment]
Hi @Kochise thanks for raising this - I wasn't aware of this incompatibility.

=> `state-machine-cat@7.1.1-beta-1` should alleviate at least part of the problem. Could you try it out and let me know?

(I did test a state machine with a lot of transparency attributes it in Inkscape 1.0.1 on a coloured background before publishing and it seemed to work quite ok - but as I don't use it on a daily basis I'm bound to overlook things).

### background

state-machine-cat isn't completely in charge of the generated svg. It produces a graph in the `dot` graph description language. After that it asks the GraphViz dot library to translate it into an svg (and GraphViz is no doubt using another library).

That said - in some places state-machine-cat does use the (apparently illegal)`transparent` as a color itself. To fix that I first replaced those with RGBA value #FFFFFF00 - but GraphViz translated that into `fill="transparent"` regardless :-/ . The fix in 7.1.1.-beta-1 uses #FFFFFF01. This tricks GraphViz into correctly generating `fill="#ffffff" fill-opacity="0.003922"` which is properly transparent for most practical purposes and more standards compliant.

> GraphViz still generates `stroke="transparent"` instead of `stroke=#000000" stroke-opacity="0"`out of its own
> volition. It's possible to brute-force our way through that (with global replaces), but if it's not necessary 
> I'd rather not do that...

**Comment by Kochise** [comment]
Will see that asap, thanks for considering the issue.

**Comment by Kochise** [comment]
https://github.com/Kochise/latex-smcat

**Comment by sverweij** [comment]
@Kochise would support for [postscript](https://graphviz.gitlab.io/doc/info/output.html#d:ps) (or its _ps2_ sibling) be helpful?

From what I recall from about 20 years ago is that LaTeX played quite well with GraphViz dot. We typically used postscript/ embedded postscript as an output format, though. If that's a thing you'd be interested in let me know; it should be fairly straightforward to implement in state-machine-cat.

**Comment by Kochise** [comment]
Looks like it indeed alleviates parts of the issue.

Yet I'd prefer GraphWiz (if it's the source of the problem) to do its job more cleanly and not rely on unsupported prehistoric drafts.

![test_7 1 0](https://user-images.githubusercontent.com/23077417/103622023-64a07e00-4f36-11eb-8166-c1b7a1db1ae8.png)
[test_7.1.0.svg.txt](https://github.com/sverweij/state-machine-cat/files/5768853/test_7.1.0.svg.txt)

![test_7 1 1-beta-1](https://user-images.githubusercontent.com/23077417/103622028-65d1ab00-4f36-11eb-9536-ccf59dde1723.png)
[test_7.1.1-beta-1.svg.txt](https://github.com/sverweij/state-machine-cat/files/5768854/test_7.1.1-beta-1.svg.txt)

**Comment by Kochise** [comment]
> 
> 
> @Kochise would support for [postscript](https://graphviz.gitlab.io/doc/info/output.html#d:ps) (or its _ps2_ sibling) be helpful?
> 
> From what I recall from about 20 years ago is that LaTeX played quite well with GraphViz dot. We typically used postscript/ embedded postscript as an output format, though. If that's a thing you'd be interested in let me know; it should be fairly straightforward to implement in state-machine-cat.

EPS is indeed my fallback format for https://github.com/Kochise/latex-mscgen because the `svg` is corrupt (same problem I guess).

    % Output file type (default is 'png', currently 'eps' as a fix, because 'svg' output cannot be trimmed and 'pdf' is non conformant)

**Comment by sverweij** [comment]
@Kochise thanks for validating this! It indeed looks better (though still not entirely what I'd expect with those texts running out of their boxes 😬) - so I've merged the PR and it'll be in a next 'regular' state-machine-cat release version (likely within a week or so).

In the mean time I've whipped up a PR (linked below) to support postscript and published it as a beta: `state-machine-cat@7.2.0-beta-1`. It supports two types of postscript: 'regular' (`-T ps`) and 'with pdf annotations' (`-T ps2`) - but I have no idea which one'd be better for use in LaTeX. 

=> Could you give it a try?

> A long time ago I re-implemented mscgen in javascript. I wrote all of the svg rendering myself and went through some
> length to make it compatible/ compliant so I could use it in Inkscape. The resulting code is not pretty (even by standards
> of 2013), but it still works quite ok.
> It's still up there in maintenance mode at [https://mscgen.js.org](https://mscgen.js.org). There even is a (hacky, big, 
> not too fast) cli version that should be call compatible with the mscgen binary (minus a few or its more esoteric options
> & output formats).

**Comment by Kochise** [comment]
> 
> 
> => Could you give it a try?

Of course, provided `pdflatex` could digest `ps` and/or `ps2` :)

> 
> 
> > A long time ago in a galaxy far far away....

What about a `latex-mscgenjs` then ? Provided I could run it on `nvm`

**Comment by Kochise** [comment]
Hi, sorry for delay...

1- Using regular `latex` file compiled with `pdflatex`, requires `eps` files (renamed `ps`) and produces blank outputs (known problem ?) :

[tmp-sample-regular-postscript.tex.txt](https://github.com/sverweij/state-machine-cat/files/5824225/tmp-sample-regular-postscript.tex.txt)
[tmp-sample-regular-postscript-pdflatex.pdf](https://github.com/sverweij/state-machine-cat/files/5824226/tmp-sample-regular-postscript-pdflatex.pdf)

[tmp-sample-postscript-with-pdf-annotations.tex.txt](https://github.com/sverweij/state-machine-cat/files/5824227/tmp-sample-postscript-with-pdf-annotations.tex.txt)
[tmp-sample-postscript-with-pdf-annotations-pdflatex.pdf](https://github.com/sverweij/state-machine-cat/files/5824228/tmp-sample-postscript-with-pdf-annotations-pdflatex.pdf)

2- Converting the `ps` file using `ps2pdf` produces the expected output, but requires a second step, which is not favored :

    ps2pdf.exe -dEPSCrop -dNOSAFER tmp-sample-regular-postscript.ps

[tmp-sample-regular-postscript-ps2pdf.pdf](https://github.com/sverweij/state-machine-cat/files/5824230/tmp-sample-regular-postscript-ps2pdf.pdf)

    ps2pdf.exe -dEPSCrop -dNOSAFER tmp-sample-postscript-with-pdf-annotations.ps

[tmp-sample-postscript-with-pdf-annotations-ps2pdf.pdf](https://github.com/sverweij/state-machine-cat/files/5824232/tmp-sample-postscript-with-pdf-annotations-ps2pdf.pdf)

At least the `postscript-with-pdf-annotations` version is automatically cropped to the useful section (yeah, the `-dEPSCrop` argument was _also_ used on the `regular-postscript` version).

Investigating in progress...

**Comment by Kochise** [comment]
3- Converting the `ps` file to `eps` before including it in the `latex` file also produces the expected output :

    ps2epsi tmp-sample-regular-postscript.ps tmp-sample-regular-postscript.eps

[tmp-sample-regular-postscript-ps2epsi.eps.txt](https://github.com/sverweij/state-machine-cat/files/5824263/tmp-sample-regular-postscript-ps2epsi.eps.txt)
[tmp-sample-regular-postscript-ps2epsi.pdf](https://github.com/sverweij/state-machine-cat/files/5824264/tmp-sample-regular-postscript-ps2epsi.pdf)

    ps2epsi tmp-sample-postscript-with-pdf-annotations.ps tmp-sample-postscript-with-pdf-annotations.eps

[tmp-sample-postscript-with-pdf-annotations-ps2epsi.eps.txt](https://github.com/sverweij/state-machine-cat/files/5824270/tmp-sample-postscript-with-pdf-annotations-ps2epsi.eps.txt)
[tmp-sample-postscript-with-pdf-annotations-ps2epsi.pdf](https://github.com/sverweij/state-machine-cat/files/5824271/tmp-sample-postscript-with-pdf-annotations-ps2epsi.pdf)

However now it's the `regular-postscript` that is bounded/cropped correctly. Go figure...

And the `eps` file is considerably larger than the original `ps` file. Try to see if you can output regular `eps` files, thanks.

**Comment by Kochise** [comment]
Possible related bugs regarding the blank output from renamed `ps` files :

2005 : https://tug.org/pipermail/macostex-archives/2005-November/018718.html
2012 : https://bugs.launchpad.net/inkscape/+bug/929463
2014 : https://tex.stackexchange.com/questions/212528/certain-eps-files-dont-convert-with-epstopdf
2016 : https://tex.stackexchange.com/questions/312011/pdflatex-call-does-not-work-with-graphics-package-and-eps-figure
2020 : https://www.mathworks.com/matlabcentral/answers/507550-eps-export-issue-blank-figure
.... : https://www.programmersought.com/article/6280225047/

Well, obviously `ps`/`eps` formats are still rather new and needs some maturation before getting production ready...

And don't even get me started on `latex` distributions/compatibilities !

**Comment by sverweij** [comment]
@Kochise thanks for your research. I always found the postscript world to be confusing. GraphViz was able to produce .eps I could include in my LaTeX build pipeline without trouble somewhere in the nineties of the last century. I must say, though, that said pipeline had postscript as its end state...

The current incarnation of GraphViz still supports encapsulated postscript (.eps) output directly. It seems to work in the compiled-to-javascript variant (viz.js) too, even though I haven't noticed it in any of its documentation (which made me hesitant earlier on). I've made a PR + accompanying beta release that also includes .eps 

=> Could you give the beta (`state-machine-cat@7.3.0-beta-1`) a spin (`smcat --output-type eps votre-machine-chique.smcat`) and see if it works in your workflow?

**Comment by Kochise** [comment]
Yeah, I'll see that asap, thanks again for your work.

**Comment by Kochise** [comment]
OK, let's call it a success...

[smcat_test.smcat.txt](https://github.com/sverweij/state-machine-cat/files/5865069/smcat_test.smcat.txt)
[smcat_test.eps.txt](https://github.com/sverweij/state-machine-cat/files/5865071/smcat_test.eps.txt)
[smcat_test-eps-converted-to.pdf](https://github.com/sverweij/state-machine-cat/files/5865073/smcat_test-eps-converted-to.pdf)

**Comment by sverweij** [comment]
Yesterday the PR was merged and released with `state-machine-cat@7.3.0`. I trust that with that (and the earlier tweaks in the dot/ svg output) this issue can be considered as fixed.

**Comment by Kochise** [comment]
Updated https://github.com/Kochise/latex-smcat to reflect your changes.

Many thanks again.
