### ISSUE TITLE
Having trouble creating multiply nested loops

### ISSUE THREAD

**Issue by asp2204** [sverweij/state-machine-cat#133]
First of all, I just wanted to say state-machine-cat is *the bomb* and is definitely the best tool I've found for making these diagrams.

### Expected Behavior
Currently, this following singly nested code works:
  
--------------
"while (1)" {
"while (fgets(c,n,stdin) > 0)" {
read_input;

a => b : c;

};

  LIVE_STREAM => dog : stop;

};

begin => read_input;
--------------

but when I try to add an extra level of nesting, I get a syntax error:
  
--------------
"while (1)" {
"while (fgets(c,n,stdin) > 0)" {
read_input;

"while (flagTextRemaining)" {
d => e : f;
};

a => b : c;

};

  LIVE_STREAM => dog : stop;

};

begin => read_input;
  
--------------

It might not even be a bug, I'm just not sure what I'm supposed to do to get multiply nested states to be visualized.

Thank you!

**Comment by sverweij** [comment]
Hi @asp2204 - thanks for the high praise 😊 

As to the state machine multiple states get separated by a `,` 

```smcat
// state declarations
initial,
a,
b,
final;

// state transitions
initial -> a;
a -> b;
b -> a;
b -> final;
```
result:
<img width="283" alt="image" src="https://user-images.githubusercontent.com/4822597/105885002-db4a0c00-6008-11eb-8642-ad69fc0ed0a7.png">


This also goes for composite states - so below there's a `,` between composite_a and composite_b:
```smcat
initial,
composite_a {
  a.initial => aa;
  aa => ab;
  ab => ac;
},
composite_b{
  ba => bb;
  bb => ba;
},
c,
final;

initial => composite_a;
ac => ba;
bb => c;
c => final;
```

result:
<img width="854" alt="image" src="https://user-images.githubusercontent.com/4822597/105885168-0f253180-6009-11eb-9c2d-af23926b2f1a.png">


In the sample under _begin => read_input_ the same goes;  the `"while (fgets(c,n,stdin) > 0)"` state has two sub-states - `read_input` and `"while (flagTextRemaining)"`. Currently they're separated by a `;` but replace them by a `,` and the parser is happy:

```smcat
"while (1)" {
  "while (fgets(c,n,stdin) > 0)" {
    read_input,

    "while (flagTextRemaining)" {
      d => e : f;
    };

    a => b : c;
  };
LIVE_STREAM => dog : stop;
};

begin => read_input;
```
result:
<img width="739" alt="image" src="https://user-images.githubusercontent.com/4822597/105884884-b8b7f300-6008-11eb-9469-322bf70bc0a7.png">


> - The parser is currently sometimes a bit cryptic when it comes to error messages - so I totally get the confusion.
> - The resulting state-diagram resembles a [nassi schneiderman](https://en.wikipedia.org/wiki/Nassi–Shneiderman_diagram) diagram - or at least something that describes application flow. Is that intentional?

**Comment by asp2204** [comment]
Thank you for the detailed response!

Yeah, I am absolutely trying to use this for software. I think I have a tendency to jump into the details too quickly when writing code, but this can be counterproductive, so I want to make more of a conscious effort to have a high-level design first.

Part of the issue I had making these in powerpoint (other than having to totally re-format everything if you want to e.g. add a step), was that it felt very detached from coding, and I had trouble really adding enough details to the diagram. I think the state-machine cat terminal interface is actually a lot better for me, because it sort of helps me mimic the more detailed headspace of coding, while still making a more high-level diagram.

Thanks again.
