### ISSUE TITLE
Publish UMD format to npm

### ISSUE THREAD

**Issue by icio** [sverweij/state-machine-cat#140]
### Context

I have some data that describes the transition of some entities' state over time and I've written a script to turn that into an state-machine-cat JSON blob so I can review that's happening. My initial setup included only an index.html, index.js and style.css.

I had hoped that I would be able load smcat from a <script> and then call [smcat.render()](https://github.com/sverweij/state-machine-cat/blob/master/docs/api.md#render-script-options-callback) as a global while I'm experimenting with throwing things together.

I had initially hoped to load state-machine-cat into the page from unpkg:

```
<script src="https://unpkg.com/state-machine-cat@8.0.0"></script>
```

But no compiled version of smcat is currently published to npm.

### Proposed Behavior

Published a [rollup build](https://rollupjs.org/) of state-machine-cat to npm.

### Current Behavior

I was able to compile state-machine-cat into a UMD myself using `npm run build` which generates a UMD version of smcat in smc.json. My package.json is:

```
{
  "scripts": {
    "build": "rollup -p @rollup/plugin-json -p @rollup/plugin-commonjs -p rollup-plugin-node-polyfills  -p @rollup/plugin-node-resolve -f umd -n smcat node_modules/state-machine-cat/src/index.js -o smc.js"
  },
  "devDependencies": {
    "@rollup/plugin-commonjs": "^19.0.0",
    "@rollup/plugin-json": "^4.1.0",
    "@rollup/plugin-node-resolve": "^13.0.0",
    "rollup": "^2.50.2",
    "rollup-plugin-node-polyfills": "^0.2.1",
    "state-machine-cat": "^8.0.0"
  }
}
```

Before I had bothered to put together the package.json, I did this with a couple of commands:

```
npm i state-machine-cat rollup @rollup/plugin-node-resolve @rollup/plugin-json @rollup/plugin-commonjs rollup-plugin-node-polyfills
node_modules/.bin/rollup -p @rollup/plugin-json -p @rollup/plugin-commonjs -p rollup-plugin-node-polyfills  -p @rollup/plugin-node-resolve -f umd -n SMC node_modules/state-machine-cat/src/index.js -o smc.js
```

I was then able to use it as:

```html
<script src=smc.js></script>
<script>
    var markup = smcat.render(
        {states: [{type: "initial", name: "initial"}]},
        {inputType: 'json', outputType: 'svg'}
    );
    var svg = new DOMParser().parseFromString(markup, 'image/svg+xml');
    document.body.appendChild(svg.documentElement);
</script>
```

You might need to add the built file to "files" in the package.json too in order for it to publish.

### Considered alternatives

I guess some extra documentation about how you might do this yourself would be a reasonable alternative to publishing a UMD-compiled version. I don't think using `<script type=module>` would work out of the bag, but I can't say that I tried it. This was just an experiment. I wanted to start playing with state-machine-cat before I was willing to commit to setting up any kind of build system.

Thanks for the great library :) Here's a preview of what I ended up building, showing the FSM reverse-engineered from our request logs of a test account:

![image](https://user-images.githubusercontent.com/408401/119971420-da21ef00-bfa8-11eb-8164-f930cc473db9.png)

**Comment by sverweij** [comment]
Hi @icio thanks for this suggestion (and that's a cool use case!!)

There is a distribution that expands html with script types `text/x-smcat`, `text/x-scxml` and `text/x-smcat-json`. It's not as flexible as having the api available in a global, but it could cover a lot of use cases. There's about 0 bytes of documentation on it, so that's an easy improvement for the coming weekend :-) 
- Script: https://state-machine-cat.js.org/state-machine-cat-inpage.min.js
- Sample use: https://state-machine-cat.js.org/inpage.html
- Sample source: https://github.com/sverweij/state-machine-cat/blob/develop/docs/inpage.html

Supplying a thing on state-machine-cat.js.org that provides the statemachine cat in global shouldn't be to hard, so holler if the above doesn't fit your need.

> on script type=module: I was in the process of converting state-machine-cat itself to ESM, but reverted the work (too little return of investment - I might consider converting to typescript instead). I see esbuid (and likely rollup and other bundles) might be able to output ESM, so I'll play around with that on the weekend.

**Comment by sverweij** [comment]
@icio as you can see in above PR I've put up a script that provides `smcat` as a global object so you can play around with it on the console. If you want to try it you can give the beta a try at https://sverweij.gitlab.io/state-machine-cat/global.html

**Comment by icio** [comment]
> There is a distribution that expands html with script types

Oh, neat! That's a great idea. I would have used this for a test page had I known about it :smile: I ended up writing something similar myself but with delayed rendering because there was loads of visualisations on the page. Not sure it'd be to everyone's tastes:

<details><summary>Source</summary>

```html
<script>
const obs = new IntersectionObserver(function(entries) {
    entries.forEach(function(entry) {
        if (!entry.isIntersecting) return;
        renderPath(entry.target);
    });
}, {
    rootMargin: '100% 0%', // Render one screen above and one screen below.
});

window.addEventListener('DOMContentLoaded', function() {
    for (let path of document.querySelectorAll('.path')) {
        obs.observe(path);
    }
});

function renderPath(target) {
    const data = target.getElementsByTagName('data')[0];
    const sm = JSON.parse(data.innerText);
    target.removeChild(data);

    const markup = SMC.render(sm, {
        inputType: 'json',
        outputType: 'svg',
        direction: data.getAttribute('data-direction') || 'left-right',
    });

    const parser = new DOMParser();
    const doc = parser.parseFromString(markup, "image/svg+xml");
    target.appendChild(doc.documentElement);

    obs.unobserve(target);
}
</script>
<body>
<div class="path"><data>
{
  "states": [
    {
      "type": "regular",
      "name": "Order(pending)",
      "color": "#586ada"
    },
    {
      "type": "regular",
      "name": "Order(fulfilled)",
      "color": "#0f823c"
    }
  ],
  "transitions": [
    {
      "from": "Order(pending)",
      "to": "Order(fulfilled)"
    }
  ]
}
</data></div>
</body>
```

</details>

> Supplying a thing on state-machine-cat.js.org that provides the statemachine cat api in a global shouldn't be too hard, so holler if the above doesn't fit your need.

I will only load a script from a third-party if I can specify an `integrity` tag, hence my preference for the versioned npm/unpkg.org route.

**Comment by sverweij** [comment]
Hi @icio thanks for that sample code. Some of that might leak into the 'inpage' script in the near future :-) 

> I will only load a script from a third-party if I can specify an integrity tag, hence my preference for the versioned npm/unpkg.org route.

That makes sense, the current URL could grow breaking changes over time. And you can't be diligent enough with loading 3rd party scripts anyway. I guess that #143 wouldn't be of much use then either, unless it'd grow the possibility to be a mini unpkg.


### On publishing an UMD/ dist to npm

Drawback of publishing bundled code to npm is that it increases the package size for the regular library. For some packages that doesn't matter a lot, but some of state-machine-cat's dependencies are _really_ big and pulling them in twice (in node_modules _and_ in a dist folder) will be noticeable.

For another diagramming library I wrote long ago (mscgenjs) I went the nine yards made a separate distribution - even though that one is almost dependency less (https://mscgen.js.org/embed.html - also available on unpkg: https://unpkg.com/mscgenjs-inpage@4.0.0/dist/mscgen-inpage.js).
