### ISSUE TITLE
TypeError with v9.0.0

### ISSUE THREAD

**Issue by mwaddell** [sverweij/state-machine-cat#148]
I'm not able to successfully import the v9.0.0 version into a project like I was with v8.x.

Using CodeSandbox, here's some example code with v8.1.1:

![image](https://user-images.githubusercontent.com/750244/126574968-3babf9a8-55b7-43c2-8075-5946c0b903bd.png)

Here's that same code with v9.0.0

![image](https://user-images.githubusercontent.com/750244/126575008-8adbea6a-f30e-4575-879e-74e7545bdb62.png)

When rendering in the browser, I'm consistently getting the error:

`Cannot read property 'smcat.template.hbs' of undefined`

**Comment by mwaddell** [comment]
Here's the codesandbox I used: https://codesandbox.io/s/state-machine-cat-v90-error-lrhcn

**Comment by sverweij** [comment]
hi @mwaddell  - thanks for reaching out on this. I've been able to reproduce it with your link and I've an idea where the problem originates. I'll keep you posted in this thread.

**Comment by mwaddell** [comment]
Thank you so much for looking into it so quickly!  It's unfortunate that things are moving so slowly in standardizing the javascript ecosystem around ESM, but I suppose it's not surprising considering how large and diverse the community is.

Thanks as always for such a great library!

**Comment by sverweij** [comment]
hi @mwaddell thanks for the kind words! ESM indeed is an interesting adventure at the moment. Next time around I'll probably choose a route that involves a transpilation layer like typescript or babel. 

In the mean time I've published `state-machine-cat@9.0.1-beta-5` - and it seems to work in a fashion backwards compatible with version 8 - here's that version applied to your reproduction sample (which has proven invaluable in testing, thanks!): https://codesandbox.io/s/state-machine-cat-v90-error-forked-5j9dw?file=/test.jsx

**Comment by mwaddell** [comment]
You're welcome - I'm currently using state-machine-cat in a react/typescript project, so I came across the issue in my GHA build but wanted to make sure it wasn't something unique to my environment, so I created the code sandbox to confirm it.  I just tested v9.0.1-beta-5 in my build environment and can confirm that it's working as it was with version 8 again.

Thanks!

**Comment by sverweij** [comment]
Thanks for the confirmation @mwaddell `state-machine-cat@9.0.1` - which includes the fix - has just been published.

(And nice to hear of a real-life use case!)

**Comment by mwaddell** [comment]
Great - thanks!

Yes, we're using state-machine-cat as part of an interactive workflow editor for the admin section of one of our applications.

![image](https://user-images.githubusercontent.com/750244/127229406-3c67777f-24bd-46f4-bc09-592d0021de12.png)

**Comment by sverweij** [comment]
Wow that looks nice! There's some elements in there I don't recognize - icons, background-colouring, styling on transitions - and some things that look like calls to action (edit, add?). How did you manage to get these in?

**Comment by mwaddell** [comment]
It's all based on PR #135 -- we maintain our internal state in JSON objects and I wrote a map/reduce function that converts from our JSON format to yours and adds classes to all of the resulting objects.  All the background and edge styling is implemented using regular CSS.  The code which adds in the icons and adds onclick/onmouseover events just looks for items by className.  We were originally using state-machine-cat to visualize existing workflows, but now we have a fully interactive editor for editing them as well.  We use this as part of a larger application which tracks how well we adhere to our standard processes.
