### ISSUE TITLE
Grammar railroad diagram

### ISSUE THREAD

**Issue by mingodad** [sverweij/state-machine-cat#150]
Using this tool https://www.bottlecaps.de/convert/ we can see a railroad diagram for the grammar in `src/parse/smcat/peg/smcat-parser.peggy` copying and pasting it on the `Input grammar:` textarea and then clicking `Convert` and then clicking `View Diagram`.

**Comment by sverweij** [comment]
Hi @mingodad I've played with it a bit and it looks interesting as a start for an addition to the documentation. Before starting to use it I'd love it to be automatable, though so it can be automatically updated when the grammar gets additions.

**Comment by sverweij** [comment]
I've found [grammkit](https://github.com/dundalek/GrammKit), which makes it possible to generated railroad diagrams for a whole peg grammmar with a cli.

It's now part of the build process - the result is at https://state-machine-cat.js.org/grammar.html
