### ISSUE TITLE
Statebox with non-ascii symbols.

### ISSUE THREAD

**Issue by merhalak** [sverweij/state-machine-cat#19]
### Expected Behavior
State box width might be sign-width independent.

### Current Behavior
State box with 2-bytes unicode signs (i.e. cyrillic) has 2x width, than text is.

### Possible Solution
Change text length calculation function.

### Steps to Reproduce (for bugs)
Create "Hello world" state, "Привет мир" state, "你好，世界" state.

### Your Environment
Atom plugin, debian 9.

**Comment by sverweij** [comment]
I've raised an issue with the viz.js project - if you want to you can follow (/ upvote :-) ) it here: https://github.com/mdaines/viz.js/issues/147

**Comment by merhalak** [comment]
Thanks.

**Comment by sverweij** [comment]
(closing as it can only be fixed upstream)

**Comment by Nakilon** [comment]
Did you guys fix it? That viz.js repo is now "archived". I face the same issue on their online page: http://viz-js.com/
