### ISSUE TITLE
Example in the documentation for a composite state with history, entry and exit actions and a set of substates

### ISSUE THREAD

**Issue by marcelbaumann** [sverweij/state-machine-cat#192]
Documentation example in the documentation for a composite state with history, entry and exit actions and a set of substates

### Expected Behavior
I am looking for a documentation showing how to declare a 
- composite state
- the composite state has a shallow history
- the composite state has an entry and an exit action
- As a composite state it has a set of substate

### Current Behavior
I am maybe too dump. I could not infer the correct syntax for such a note. It is clear how to create a composite state with substates and history or a state with entry and exit actions. But I could not find out how to do both.
_Such a situation exists as described in the UML statechart documentation_.

### Possible Solution
Please extend the cool readme with this additional example.

### Steps to Reproduce (for bugs)
_missing in the readme_

### Context
Documentation missing. I have such FSM. The visual quality of state machine cat is awesome so I would like to display my FSM with it instead of PlantUML.

### Your Environment
Used to online tool to validate syntax and display the diagram.

Thanks for this cool tool. I hope you can just extend the documentation with this example.

Sincerely

**Comment by sverweij** [comment]
Hi @marcelbaumann thanks for this feedback! 

I gather you mean something like this?

<img width="703" alt="image" src="https://github.com/sverweij/state-machine-cat/assets/4822597/d298d023-bf06-4225-8e6e-1d989b08a98b">


You can get that with the following smcat script:

```smcat
atomic: 
    entry/ entry for atomic 
    exit/ exit for atomic
    an activity,
composite: 
   entry/ entry action for composite state
   exit/ exit action for composite state
   an activity for composite state
{
    composite.history,
    "sub state a":
      entry/ entry for a
      exit/ exit for a
      an activity for a,
    "sub state b",
    c,    
    composite.final;
    
    "sub state a" => "sub state b";
    "sub state b" => c;
    c => "sub state a";
    c => composite.final;

};


initial => atomic;
atomic => composite;
```

It's indeed not immediately obvious where to put these actions relative to the state machine within the `composite` state. If this is indeed what you're looking for, I'll add it to the readme.

**Comment by marcelbaumann** [comment]
Exactly the information I was looking for. Thanks a lot.
I have the diagrams created by hand as expected. Additionally, I extended my generator to support the correct syntax.

I think it is worth to add to the README file.

Thanks for the fast answer.

**Comment by sverweij** [comment]
Found I hadn't updated the README with an example on how to do do _activities_ (like entry & exit triggers) on composite states yet. That's now [corrected](https://github.com/sverweij/state-machine-cat#nested-state-machines) in commit 976f32a.
