### ISSUE TITLE
Initial state

### ISSUE THREAD

**Issue by qarlosalberto** [sverweij/state-machine-cat#202]
I have a state named "initial". Is it possible to show it as a normal state?

**Comment by sverweij** [comment]
Hi @qarlosalberto - yes it is! You can use the `type` attribute for that - see [overriding the ype of a state](https://github.com/sverweij/state-machine-cat#overriding-the-type-of-a-state) in the README

**Comment by qarlosalberto** [comment]
Thanks!!!!
