### ISSUE TITLE
Include your module in typescript

### ISSUE THREAD

**Issue by sparkitny** [sverweij/state-machine-cat#21]
Hi,

never done it before, but hopefully I'm not the only one trying do use it in a typescript environment.

Do you have a short and clean example of how to include your lib in an Angular project?

Thanks in advance

**Comment by sverweij** [comment]
hi @sparkitny  - I'm not well versed in Angular. I _can_ give an example of how to use state-machine-cat in typescript, though if that helps:

```typescript
import {IRenderOptions, render} from "state-machine-cat";

try {
    const RENDEROPTIONS: IRenderOptions = {
        // inputType: "smcat",
        // engine: "dot",
        // direction: "top-down",
        outputType: "svg",
    };
    const lSVGInAString: string = render(
        `
            initial => backlog;
            backlog => doing;
            doing => test;
        `,
        RENDEROPTIONS,
    );
    /* now do interesting stuff with the resulting svg, like putting
       it in a DOM element ...
    */
    console.log(lSVGInAString);
} catch (pError) {
    console.error(pError);
}

```

(`state-machine-cat` exposes its typescript type definitions in a standard way, so you get some type-checking and if your IDE supports typescript you'll get autocompletion & stuff)


Out of curiosity: What will you be using state-machine-cat for?

**Comment by sparkitny** [comment]
Hi,

That should do the trick. I simply didn't know, how to import as JavaScript always require packages and typescript is more like object oriented languages 

I'm going to visualize a state machine better said a process with all it's States and edges.
