### ISSUE TITLE
New Direction

### ISSUE THREAD

**Issue by ambagasdowa** [sverweij/state-machine-cat#25]
It is possible to add the address from bottom to top

**Comment by sverweij** [comment]
hi @ambagasdowa 

If you mean to add an option to render e.g. `a => b: hello;` as ![bottom-to-top](https://user-images.githubusercontent.com/4822597/46439915-308bf080-c762-11e8-8afd-bbfa8475f71f.png) ...

... yes, that is possible, and I'd consider it an excellent suggestion. 

=> In what situation would you use it?

**Comment by ambagasdowa** [comment]
Thank you very much, that's just what I needed, I'm starting to use smcat at work, also for a personal documentation project and it's in this one that I needed to render from the bottom-up. Excellent work!

**Comment by sverweij** [comment]
I've published state-machine-cat@4.1.0-beta-2 (both on npm and on state-machine-cat.js.org) which fixes an orientation bug with fork/ join pseudo states that occurred  with the new  bottom-top direction.

**Comment by sverweij** [comment]
@ambagasdowa - it's now published on npm as latest (state-machine-cat@4.1.0) and on state-machine-cat.js.org.
