### ISSUE TITLE
Specifying output dimensions or ratio

### ISSUE THREAD

**Issue by slhck** [sverweij/state-machine-cat#33]
Thank you for this awesome project ❤️ — this is more of a feature request / support issue. I don't have much experience with GraphViz, so please excuse me if I'm missing something obvious.

### Expected Behavior

For charts that could potentially be large, it would be helpful to be able to specify the ratio or output dimensions so that graphs are properly laid out.

### Current Behavior

When I produce an SVG with the following smcat code:

```
initial,
undefined,
fooState {
  foo -> bar: barEvent;
  foo -> baz: bazEvent;
  bork -> foo: fooEvent;
  bork -> bar: barEvent;
  foo -> bork: borkEvent;
  foo -> bar: barEvent;
  foo -> baz: bazEvent;
  bar -> foo: fooEvent;
  bar -> baz2: bazEvent;
  baz -> bork: borkEvent;
  baz -> foo: fooEvent;
  baz -> bar: barEvent;
  baz2 -> bork: borkEvent;
  baz2 -> foo: fooEvent;
  baz2 -> bar: barEvent;
},
initFooState {
  initbar -> initFoo: bazEvent;
  initFoo -> foo: fooEvent;
  initbar -> foo: fooEvent;
};

initial -> undefined;

undefined -> foo: fooEvent;

undefined -> initFoo: bazEvent;
undefined -> initFoo: unstartedEvent;
undefined -> initbar: barEvent;

initFoo -> bork: borkEvent;
```

… using left-to-right layout, I get quite a wide image:

![image](https://user-images.githubusercontent.com/582444/47723328-9631a680-dc54-11e8-90c3-e1ece32ce6bf.png)

Using the default, the labels and arrows are overlapping quite often:

![image](https://user-images.githubusercontent.com/582444/47723742-751d8580-dc55-11e8-927b-d2d64dff3ef6.png)

Hence, I chose the LTR variant.

### Possible Solution

Could the layout options for rendering the output be somehow specified, e.g. using a `-r` option?

I imagine a parameter that would set the `ratio` such as described here: https://www.graphviz.org/doc/info/attrs.html#d:ratio

### Your Environment

* Version used: 4.2.0
* Node version: v11.0.0
* Operating System and version: macOS 10.13

**Comment by sverweij** [comment]
hi @slhck thanks for raising this issue. It has annoyed me for a while as well - this gives me an incentive to seriously attempt a fix.

IMHO the left-to-right graph needs to look better out of the box for the majority of cases, without the need for manual tweaking; so that's what I'm going to try first. If that fails, I'll look into exposing the underlying interface (e.g. by passing on node separation, ratio and/ or other graph level tweaks).

**Comment by sverweij** [comment]
hi @slhck I've made a little tweak that should help in many cases (see PR #34 ☝️ ). I've published it on npm as 4.3.1-beta-1 and you can try it on line on https://sverweij.gitlab.io/state-machine-cat .

I'll keep on tweaking, but wanted to share this little step anyway

This is how the sample you provided looks with the tweak:
![sample](https://user-images.githubusercontent.com/4822597/47937949-beced000-dee2-11e8-98b5-c23228c1ab46.png)

**Comment by sverweij** [comment]
The PR is merged and the changes are released in the (regular) 4.3.1 release, both on npmjs and in the online interpreter.

There's some graph level parameters I still want to expose in a similar fashion as the `direction` one - hence I propose to keep this issue open until that hits master (unless you consider the tweak _good enough_  to fulfil it).

**Comment by slhck** [comment]
I was out of town for a while, so I only saw those changes now. Looks much better now, thank you!

About leaving this open and having a ratio / dimensions parameter, I'll leave this up to you. Being able to specify a ratio and dimensions would be tremendously helpful in case someone wants to put these kinds of charts into documents, where, say, only a particular proportion of the page should be filled, but keeping the font size somewhat predictable.

I do this when generating graphics from R, for example, to keep font sizes and proportions equal across different documents and charts that have different content.

**Comment by sverweij** [comment]
Thanks for the rationale for adding the ratio/ dimensions parameters. 

Graph level parameters will probably follow in the course of this week - I'll keep you posted. 

B.t.w. until that has landed, as a quick hack, you can insert graph level parameters using the native dot's `-G` command line parameter. E.g. to get output that is as high as it's wide and has a width of 8 inch you could use:
```sh
smcat --direction left-right -T dot -o - your_statemachine.smcat | dot -Tsvg  -Gsize="8,0" -Gratio=1 > your_statemachine.svg
```

(Similarly you can use `-N` and `-E` attributes to set things for all nodes and edges respectively)

**Comment by sverweij** [comment]
hey @slhck version 4.4.0-beta-4 is now on npm.  With it you can pass on dot graph parameters with a `--dot-graph-params` option, e.g. like so:

```sh
smcat --direction left-right --dot-graph-params "ratio=1 size=\"8,0\"" your_statemachine.smcat
```

(It's also possible to pass these things to the online interpreter - see #36 for details)

**Comment by slhck** [comment]
That sounds great — I guess that's a good compromise between enabling exposing the parameters but not manually adding one for everything that could potentially be relevant. I've tried it with different ratios and it does exactly what I had in mind originally. Thanks for your efforts!

**Comment by sverweij** [comment]
Thanks for testing it & getting back so quickly!

(there's some polishing to do here & there still (e.g. documentation) - I hope to publish to mainstream beginning of next week).

**Comment by sverweij** [comment]
FYI: 
- I've renamed the `--dot-graph-params` to --dot-graph-attrs` [GraphViz](https://graphviz.gitlab.io/_pages/doc/info/attrs.html) calls them  _attributes_.
- In the near future state-machine-cat might grow some `--dot-node-attrs` and `--dot-edge-attrs` as well
