### ISSUE TITLE
Typo in mediaplayer example

### ISSUE THREAD

**Issue by kiloboot** [sverweij/state-machine-cat#38]
https://github.com/sverweij/state-machine-cat/blob/d6c7dc0587e7f3ee9025a8f43a5973a68f05e1df/docs/samples/mediaplayer.smcat#L10
should be 'play' instead of 'pause'

**Comment by sverweij** [comment]
@kiloboot - thanks for noticing; I wondered when someone would 😃 

The media player model in my head when I made that sample was that of a 1990's cassette deck:

![media-player-ux](https://user-images.githubusercontent.com/4822597/52806188-a72de880-3088-11e9-9b1b-9c00766c2b20.png)

If you wanted to pause the cassette playing, you'd press pause (`||`) - which disengaged the motor from the drive train, but left the play & record heads in place. In the mean time the play (`>`) button would remain in the depressed state. The way to start playing again was to press pause again, which would re-engage the motor.

I feel old.

Modern media players have UX models where resuming play is closer to the user's intent. Pressing play typically resumes play - and this is also what reflects your expectation.

For a first example this should be closer to what most people encounter so it's as clear as possible => change underway.

**Comment by sverweij** [comment]
fixed in [ae0a729](/sverweij/state-machine-cat/commit/ae0a729f6250bf195d7742b2bc722903a9ff7a20)
