### ISSUE TITLE
how to specify coordinate

### ISSUE THREAD

**Issue by cuichanghao** [sverweij/state-machine-cat#41]
how to specify object position? like x,y coordinate.

**Comment by sverweij** [comment]
The goal of state-machine-cat is unburden the user from doing any manual layout, and taking care of it automatically. This is why specifying coordinates is not part of the language. There are some ways to influence how the diagram gets rendered - by picking a different engine, or a direction in which elements get rendered.

So the short answer is: you cannot.

What's the reason you'd like to specify coordinates?
