### ISSUE TITLE
Escaping node names that contain "initial" or "final"

### ISSUE THREAD

**Issue by jogloran** [sverweij/state-machine-cat#42]
Is this possible? It seems that any node name that has initial or final as a substring will become special nodes.

**Comment by sverweij** [comment]
Hi @jogloran thanks for raising this.

At the moment you can only work around it, by using a label and an alternative node name (documented below). Which is not ideal. So I have created an initial fix that does allow overrides (see further down for details).

=> Can you let me know if that works for you?

### workaround (up till version 4.4.8):
E.g. in this (contrived) example ...
```
initial,
"retrieving initials",
"retrieving surname",
"finalizing draw",
final;

initial => "retrieving initials";
"retrieving initials" => "retrieving surname";
"retrieving surname" => "finalizing draw";
"finalizing draw" => final;
```

... to make sure the state "retrieving initials" isn't rendered as an an initial state, and "finalizing draw" not as a final state ( 😬 ) ...:
<img width="355" alt="screenshot 2019-03-05 at 18 51 47" src="https://user-images.githubusercontent.com/4822597/53825978-d80e8880-3f77-11e9-92d6-75f766ea2439.png">

... rename the state and put the original state name in a label ...: 
```
initial,
"retrieving intls" [label="retrieving initials"],
"retrieving surname",
"fnlzing draw" [label="finalizing draw"],
final;

initial => "retrieving intls";
"retrieving intls" => "retrieving surname";
"retrieving surname" => "fnlzing draw";
"fnlzing draw" => final;
```

Resulting in this:
<img width="571" alt="screenshot 2019-03-05 at 18 47 00" src="https://user-images.githubusercontent.com/4822597/53825725-3c7d1800-3f77-11e9-95f4-e4485b152089.png">

### probably a better solution (planned as of version 4.5.0)
That workaround is klunky, so I've introduced an extra attribute, which you can use to override the type of a state and you can more simply write:

```
initial,
"retrieving initials" [type=regular],
"retrieving surname",
"finalizing draw" [type=regular],
final;

initial => "retrieving initials";
"retrieving initials" => "retrieving surname";
"retrieving surname" => "finalizing draw";
"finalizing draw" => final;
```

Available _now_ on 
- http://sverweij.gitlab.io/state-machine-cat
- npm as a beta; version: `state-machine-cat@4.5.0-beta-1`

**Comment by jogloran** [comment]
This works for me! Since "initialise", "finalise" and similar terms are pretty common explicit state names, I think this workaround is going to help a lot of people.

**Comment by sverweij** [comment]
Great! @jogloran Thanks for the fast check. I'm currently doing some polishing - and will later add the attribute to the tutorial/ manual. Will probably publish a regular version later this week (I'll ping in this thread).

**Comment by sverweij** [comment]
4.5.0 is now live on npm, https://state-machine-cat.js.org and on https://sverweij.gitlab.io/state-machine-cat. Thanks again for raising this issue!
