### ISSUE TITLE
XMI output file format

### ISSUE THREAD

**Issue by EduardShaid** [sverweij/state-machine-cat#44]
Can I still enter the XMI output file format ?

**Comment by sverweij** [comment]
While  state-machine-cat _does_ support [W3C SCXML](https://www.w3.org/TR/scxml/) as an output format it does not support XMI as input or output format (assuming you're refering to [the OMG's XML Metadata Interchange Specification](https://www.omg.org/spec/XMI/)) at the moment.

What'd you be using XMI input (or output) for?

**Comment by EduardShaid** [comment]
There is a good project https://github.com/jonpe960/ufsm, that uses the XMI format. It would be interesting to combine these two projects.

**Comment by sverweij** [comment]
If I deduce correctly from [this](https://github.com/jonpe960/ufsm/issues/12) and [this](https://github.com/jonpe960/ufsm/issues/10) issue you filed with ufsm you'd like to have an environment to specify state charts in - and use ufsm to generate code from it. 

Just to be an alternative to big DnD tools I've made a first working implementation (the ufsm DHCP sample works) of an xmi-reporter which will be on npm and an on line test url in the coming days - I'll give a ping in this thread with more information.

> (If anyone wants xmi as an _input_ for state-machine-cat, though: I'm not against that (PR welcome), but I'm not going to work on it unless accompanied by a sufficient enticement (💸 ) to make it worth my while. I've parsed xmi in the past and that's not an experience I'd like to repeat in my spare time without recompense.).

**Comment by sverweij** [comment]
@EduardShaid  I've published version 4.6.0-beta-1 with my first (verified) stab at an xmi renderer (details below). It would be awesome if you could give it a spin and give me feedback!

- web site beta on gitlab: http://sverweij.gitlab.io/state-machine-cat/
- on npm as `state-machine-cat@4.6.0-beta-1`

(There will be border cases (and maybe straight out normal cases) that won't behave as expected yet - hence the beta ...)

### Screenshot
<img width="931" alt="xmi-output-option" src="https://user-images.githubusercontent.com/4822597/55292662-ec666980-53ed-11e9-8cc0-723f62b21cfc.png">

**Comment by EduardShaid** [comment]
Very good !
But there is a counter question: how fully do you implement the capabilities of the statechart UML ? Please see these features in the "Supported UML statechart features:" table at https://github.com/jonpe960/ufsm.

**Comment by sverweij** [comment]
state-machine-cat has close to 100% parity with UML.

You can compare for yourself with the features in the [language tutorial](https://github.com/sverweij/state-machine-cat#the-language). 

What you'll see missing is some more esoteric ones I ddi
- junction - (which is just a forkjoin with multiple inputs and outputs - so technically it's already supported)
- terminate - (which is just an alias for the _final_ state)
- explicit entry and exit _points _(which are convenience notations for _initial_ and _final_ within a nested stated)

**Comment by sverweij** [comment]
@EduardShaid - in the mean time: there's a new beta on npm (`state-machine-cat@4.6.0-beta-5`) and [gitlab](https://sverweij.gitlab.io/state-machine-cat) that now generates xmi with UML compliant naming for activities and (pseudo-) states state-machine-cat supports. I've also included explicit junction and termination pseudo state support (in a separate PR - see #46) in that beta.

If you can find the time - I'd love to hear any feedback on how the beta works out for you.
