### ISSUE TITLE
Issue with choice and syntax

### ISSUE THREAD

**Issue by ajRiverav** [sverweij/state-machine-cat#53]
A choice declaration causes a syntax. 
### Expected Behavior

No syntax error. 

### Current Behavior

Get syntax error.
### Steps to Reproduce (for bugs)

1. Input type set to SMCAT
2. Output type set SVG
3. Type in following SMCAT code
```
// the following line produces error
// "SyntaxError: Expected comment, end of input, line end, or 
// whitespace but "^" found."
^authenticated?: is user authenticated?

//
// State actions definitions
//
Authentication:
"check if google token exists
if yes, authenticate user
if no, sign up";

//
// State Machine
//
initial => Launch; 
Launch -> Authentication;


Authentication -> ^authenticated?;

^authenticated? -> Home: no;
^authenticated? -> SignUp: yes;

Home -> final;
SignUp -> final;
```

### Context

This causes the SVG to not show a description for choice "authenticated"
### Your Environment

Using the online interpreter.

**Comment by ajRiverav** [comment]
Ok. As far as this issue, this ticket can be closed. 
If you want to create another to tackle the syntax error, go ahead. 
👍

**Comment by sverweij** [comment]
Error message feedback needs to be improved any way - it's [on the backlog](https://github.com/sverweij/state-machine-cat/projects/1#card-22082621) since a few seconds.
