### ISSUE TITLE
substate appearing in wrong superstate

### ISSUE THREAD

**Issue by ajRiverav** [sverweij/state-machine-cat#55]
In the online interpreter, put 
State Z shows up in different superstate depending on the code order. 

I am expecting to see state Z in superstate Y. However, depending on how one orders the code, it may appear in superstate A or Y. How does one ensure Z is always a substate of Y

![image](https://user-images.githubusercontent.com/22076301/58502256-35b80880-8154-11e9-96e2-3d6e57fd3e43.png)

vs

![image](https://user-images.githubusercontent.com/22076301/58502291-3fda0700-8154-11e9-9a4e-e3c7eec99909.png)

**Comment by sverweij** [comment]
hi @ajRiverav. Short answer: declare the sub state explicitly in the super state you want it to exist:

```
Y {
    X, Z;
    
    X => Z;
},
A {
    B, C;
    
    B => C;
    C => B;
    C => Z;
};
```

### longer answer
In the example you provided, state-machine-cat has to make a choice to which Z belongs. It goes from top to bottom, sees an X as part of Y and a Z as part of Y and declares them there. When it processes entity A it sees B, C and Z. B and C aren't declared yet, and go under A. Z is already declared in Y so it'll use that.

Typically this algorithm (`top > down`, `deep > shallow`) does a good job of guessing what you intend, but in case it doesn't you can declare states explicitly (which why there's also the rule `explicit > implicit`).

### something that might help
The on line interpreter has `smcat` as one of its output formats. That seems daft, but if you feed it a chart without explicit declarations it adds them for you. I got the smcat script above by feeding this as an input:

```
Y {
    X => Z;
},
A {
 
    B => C;
    C => B;
    C => Z;
};
```

HTH
