### ISSUE TITLE
Conversion of ornamental pseudo-states to SCXML could be more elegant

### ISSUE THREAD

**Issue by EduardShaid** [sverweij/state-machine-cat#66]
There is a wrong conversion to the SCXML format for junction, choice, fork, and join. View the document:

https://www.w3.org/TR/2005/WD-scxml-20050705/#N1096F

**Comment by sverweij** [comment]
Thanks for the suggestion and the reference.

How to handle  junctions, choices, forks and joins ('ornamental pseudo-states') is a matter of taste, as open issue A5 in that document makes clear. I agree with the argument that converting them to full-fledged states is not the most elegant way to handle them, but it is not incorrect. I've documented the decision in [SCXML.md](https://github.com/sverweij/state-machine-cat/blob/develop/docs/SCXML.md#fork-join-and-junction-pseudo-states). A more elegant solution is to [de-sugar the pseudo-states](https://github.com/sverweij/state-machine-cat/blob/develop/docs/desugar.md) - which is a future feature.

=> How does the way state-machine-cat emits these pseudo-states inconvenience you?

> B.t.w. the document you refer to is the 2005 draft of the standard; the latest version of the SCXML standard is from 2015. The 2015 version doesn't have a recommendation on how to handle these pseudo states
