### ISSUE TITLE
SVG Output sometimes broken

### ISSUE THREAD

**Issue by hauau** [sverweij/state-machine-cat#7]
Svg output sometimes produces distorted lines.

### Current Behavior

`direction: 'left-right'`
[svg source](https://my.mixtape.moe/strmig.svg)
![png render](https://i.imgur.com/ees6MI1.jpg)
1. Notice distorted `idle` state border
2. Notice crossing transitions

`direction: 'top-down`
[svg source](https://my.mixtape.moe/wfutwh.svg)
![png render](https://i.imgur.com/LAgqJoA.jpg)
1. Notice transition lines geometry
2. Notice arrow placement with respect to transitions

### Steps to Reproduce (for bugs)
Try to `smc.render` from following input:

```
initial => idle;
idle => pending: REQUEST;
pending => fulfilled: SUCCESS;
pending => rejected: FAILURE;
fulfilled => pending: REQUEST;
rejected => pending: REQUEST;
```

### Your Environment
nodejs 9.4.0, smc 2.2.1

**Comment by sverweij** [comment]
hi @hauau - thanks for reporting this! That doesn't look right indeed.

I can't reproduce it though :-/, both using state-machine-cat 2.3.0 on nodejs 9.8.0 and state-machine-cat 2.2.1 on node 9.4.0. This means there's another difference in our set ups.

- What program do you use to view the svg's with (/ render to png)? 
- What OS are you on? (I don't think that'd matter for this, though). 

Also: could you try with the on line interpreter (in an up to date firefox/ chrome or safari browser) and see if the problem occurs there as well?

As a side note: The weird inward bump in the left-right rendering and the slightly spasmodic arcs in the top-down rendering are clearly wrong. However, viz.js (or actually: [GraphViz](http://www.graphviz.org)) which state-machine-cat uses for graphics rendering can't always prevent lines from crossing. 

<img width="553" src="https://user-images.githubusercontent.com/4822597/37566770-da39d76a-2abd-11e8-96b2-55896ee7beee.png">

<img width="331" src="https://user-images.githubusercontent.com/4822597/37566788-0dfecd1c-2abe-11e8-8fac-2d0b2271c61c.png">

**Comment by sverweij** [comment]
I see the svg's you posted now. They look as wrong in any browser here as they do in the png renditions in your report. I did a [comparison between your svg's and mine](https://gist.github.com/sverweij/cbf0b74c94f9f2452fd51108f29dcad7/revisions?diff=split#diff-b9e747e913a3e91ed52b82c5d5ed540c) and in the version from the original issue (in pink) a space missing on line 20 between `-27.732` and `103.779`, which makes one of the coordinates `-27.732103.779` - that explains the inverted nose in the left-right sample in your report. I can't explain how that space got missing with exactly the same versions of smcat and viz.js. 

How do you write the svg?

(In the previous comment I used the command line interface. Just to make sure there's as little difference between your and my reproduction scenario - here's the snippet I've used to produce the above gist):
```javascript
const smcat = require("state-machine-cat");

try {
    const lSVGInAString = smcat.render(
        `
        initial => idle;
        idle => pending: REQUEST;
        pending => fulfilled: SUCCESS;
        pending => rejected: FAILURE;
        fulfilled => pending: REQUEST;
        rejected => pending: REQUEST;
        `,
        {
            outputType: "svg",
            direction: "left-right"
        }
    );
    console.log(lSVGInAString);
} catch (pError) {
    console.error(pError);
}
```

**Comment by hauau** [comment]
>How do you write the svg?

Thank you, that's totally it :D I copypasted output from my terminal and it introduced whitespace. I already verified it in win vm and every browser and cli smc, and everything works as expected. Ok that's was a silly mistake, sorry for wasting your time.
