### ISSUE TITLE
style a node results in different layout

### ISSUE THREAD

**Issue by Jiajun-Deng** [sverweij/state-machine-cat#71]
First of all, thank you for your amazing package! I upgraded webpack and did some work around and it worked!
I came across some issues here. I'm not sure they are bugs or the way I used this lib is wrong.

When I changed the style of different nodes, the graph layout could be totally different.

> Below is the syntax that define the graph.
```
ACTIVE_STATES{IDLE,EXECUTE,HELD;},INIT_STATES{STOPPED;},ABORTED;
IDLE=>EXECUTE:Start;
EXECUTE=>IDLE:Execute_SC;
EXECUTE=>HELD:Hold;
HELD=>EXECUTE:Unhold;
ACTIVE_STATES=>STOPPED:Stop;
ACTIVE_STATES=>ABORTED:Abort;
STOPPED=>IDLE:Stopped_Reset;
INIT_STATES=>ABORTED:Abort;
ABORTED=>STOPPED:Clear;
```
### Expected Behavior

I think the layout should stays the same.
### Current Behavior

> Highlight IDLE by `IDLE [color = "red"]`,
![Screen Shot 2019-08-07 at 8 14 04 PM](https://user-images.githubusercontent.com/46533014/62668129-45bc4780-b950-11e9-8a48-6fe200d757b2.png)

> Highlight HELD by `HELD [color = "red"]`,
![Screen Shot 2019-08-07 at 8 14 22 PM](https://user-images.githubusercontent.com/46533014/62668136-4a80fb80-b950-11e9-920d-66a104710d76.png)

> Want to highlight EXECUTE by `EXECUTE [color = "red"]`, got weird error.
![Screen Shot 2019-08-07 at 8 15 11 PM](https://user-images.githubusercontent.com/46533014/62668170-6be1e780-b950-11e9-9b88-cfe7ec273504.png)

> Try to highlight a level 1 node like ABORTED by `ABORTED [color = "red"]`, but nothing changed.
![Screen Shot 2019-08-07 at 8 20 13 PM](https://user-images.githubusercontent.com/46533014/62668242-caa76100-b950-11e9-8e2d-2310ef696496.png)

### Possible Solution

I'm not sure the way I change the style of a node is the only way or not. May you have better solutions.

### Steps to Reproduce (for bugs)

1. I pasted the smcat syntax I used.
2. The syntax was generated in three parts: the node needs to be highlighted, all the nodes(with nested relationships) and all the transitions.

### Context

The graph layout changes may be annoying since I prefer more stable visualization of state machines.
I'd like to highlight any nodes(which has no substates no matter what level it is).

### Your Environment

* Version used: 5.1.1
* Node version: 12.0
* Operating System and version: mac os
* Link to your project: null

**Comment by sverweij** [comment]
hey @Jiajun-Deng I've tried to be reproduce but couldn't until I realized you're probably adding the state you want to highlight as an extra state, like so:

```smcat
ABORTED [color="red"], // added to highlight
ACTIVE_STATES {
    IDLE,
    EXECUTE,
    HELD;
},
INIT_STATES {
    STOPPED;
},
ABORTED; // second definition of the ABORTED state - will overwrite the above one, so no red highlights anymore ...

IDLE => EXECUTE: Start;
EXECUTE => IDLE: Execute_SC;
EXECUTE => HELD: Hold;
HELD => EXECUTE: Unhold;
ACTIVE_STATES => STOPPED: Stop;
ACTIVE_STATES => ABORTED: Abort;
STOPPED => IDLE: Stopped_Reset;
INIT_STATES => ABORTED: Abort;
ABORTED => STOPPED: Clear;
```

Did I infer that correctly? If so, that explains the behavior you face.

The way to use `color` (or `active`) attributes is to add them to the existing state. E.g. to color ABORTED red, you'd do this:

```smcat
ACTIVE_STATES {
    IDLE,
    EXECUTE,
    HELD;
},
INIT_STATES {
    STOPPED;
},
ABORTED [color="red"]; 

IDLE => EXECUTE: Start;
EXECUTE => IDLE: Execute_SC;
EXECUTE => HELD: Hold;
HELD => EXECUTE: Unhold;
ACTIVE_STATES => STOPPED: Stop;
ACTIVE_STATES => ABORTED: Abort;
STOPPED => IDLE: Stopped_Reset;
INIT_STATES => ABORTED: Abort;
ABORTED => STOPPED: Clear;
```

![image](https://user-images.githubusercontent.com/4822597/62696992-f6225e00-b9d9-11e9-88c0-0c0d779cbabc.png)

In this way also the layout of the diagram will stay consistent.

HTH

**Comment by Jiajun-Deng** [comment]
Morning @sverweij , thank you so much! It did solve my problem perfectly.
One more question, in which version of smcat you used viz.js@1.8.0? I may rollback to that version because we don't have viz.js@1.8.3 available.

**Comment by Jiajun-Deng** [comment]
I tried to udgrade the nested dependency you use viz.js to 2.1.2 version. It works fine. 

https://stackoverflow.com/questions/15806152/how-do-i-override-nested-npm-dependency-versions

I think you may try to upgrade some of the dependencies. Since some of them are kind of old.

**Comment by sverweij** [comment]
@Jiajun-Deng Glad the solution worked

On dependencies - only viz.js is not on latest - which is a [conscious decision](https://github.com/sverweij/state-machine-cat/blob/develop/package.json#L52). Other dependencies are outdated at most a week - they're updated  to _latest_ each release (e.g. for @5.0.0 it's the devDependencies `upem` and `husky` which are one patch version behind)

It'd be good news if viz.js 2.1.2 would actually work for your situation. Last time I tried to incorporate it though, the automated non-regression test set indicated no svg could be generated successfully.

What is the reason viz.js@1.8.3 is not available for your project? What does "not available" mean in this case? npmjs.com has it, as do its mirrors - and that's where you (probably?) retrieved state-machine-cat as well

**Comment by Jiajun-Deng** [comment]
I'm using an inner npm repository. viz.js@1.8.2 can not be fetched in the repository. Maybe later the newer version of viz.js like 2.1.2 will be available. But sadly state machine cat can't use it... 
Do you have any bundled smcat.js available? Like I can include this bundled package in /lib/, without bundling by webpack and still can import in my .js file? Will this be possible?
