### ISSUE TITLE
show multiple graphs in a single page

### ISSUE THREAD

**Issue by Jiajun-Deng** [sverweij/state-machine-cat#75]
I don't if this feature is already available or not.
I'd like to use state-machine-cat to show several graphs in a single page. .
### Context

I can image I need to set up different containers with different id. How about the svg generated in smcat.render()? Shall I assign an id for each generated svg? I think in this package there should be a portal for us to do so.
### Proposed Behavior

I tried to do so and thought the render graph action should run correctly. Like each syntax generated corresponding svg and each svg displys in corresponding div.innerHtml.
### Current Behavior

The smcat.render() threw an error.

Hope you can think about this. Thanks.

**Comment by sverweij** [comment]
Hi - it's possible to have more than one rendition on a single page. Last night I wrote a  sample  to be sure it still works. It's a scripts that runs after page load. For each <script> element in the page it can digest, it renders a state diagram

- Source: [html](https://github.com/sverweij/state-machine-cat/blob/develop/docs/inpage.html), [javascript](https://github.com/sverweij/state-machine-cat/blob/develop/docs/state-machine-cat-inpage.js) and [webpack config](https://github.com/sverweij/state-machine-cat/blob/develop/webpack.inpage.config.js)
- You can see it on [the state machine cat deployment on gitlab.io](http://sverweij.gitlab.io/state-machine-cat/inpage.html).

=> can you supply what error smcat.render() threw?

**Comment by Jiajun-Deng** [comment]
@sverweij 
Yes, you are right! I did work it out. Thank you for replying so fast. 
Also, I'd like to work on another feature, changing the whole svg's theme instead of only several nodes or edges. For example, if I want to show the graph in black background, the svg will be inverted in color, white in text/lines and black in filling color. 
I think this will be cool. I've tried another package --mermaid before, this package can change theme easily. https://mermaidjs.github.io/#/

**Comment by sverweij** [comment]
hi @Jiajun-Deng It's possible to do styling. I just realised it's thoroughly undocumented, though, so here's a short write-up I'll put in the documentation later on. 

Let me know if it helps 

### Styling state machine graphics

Under the hood state-machine-cat uses GraphViz dot. It's possible to manually tweak and/ or post-process the dot it generates. However, state-machine-cat has some ways to pass styling attributes to GraphViz, which might be an easier option.

> state-machine-cat passes the styling attributes directly to GraphViz. This means you
> can use everything documented on the GraphViz website under [Node, Edge and Graph Attributes](https://graphviz.gitlab.io/_pages/doc/info/attrs.html), but also that it doesn't
> validate what it passes.
>
> If you're not familiar with GraphViz - there's a small appendix below that runs
> throught the basics as relevant for use within state-machine-cat. For detailed
> documentation you're best off checking [graphviz.org](https://graphviz.org)

Below we'll use the state machine of a cassette player, which we want to give a slightly more 'engineering look'; a blue background, white lines and a mono spaced font. Without any modifications it'd look like this:

![regular](https://user-images.githubusercontent.com/4822597/63228236-758d0a00-c1f0-11e9-9ec8-25a2e6833307.png)

After we're done it'll look closer to this:

![cassetteplayer](https://user-images.githubusercontent.com/4822597/63228244-85a4e980-c1f0-11e9-990e-ee904478783e.png)

<details>
<summary>source</summary>

```smcat
initial,
off,

on {
  stopped, playing, paused;

  stopped => playing : play;
  playing => stopped : stop;
  playing => paused  : pause;
  paused  => playing : pause;
  paused  => stopped : stop;
};

initial => off;
off     => stopped : power;
on      => off     : power;
```

</details>

#### Using the command line

The command line interface sports three options to pass attributes to dot; `--dot-graph-attrs` `--dot-node-attrs` and `--dot-edge-attrs`. Each of them pass styling parameters to GraphViz, on respectively graph, node (the _states_) and edge (the _transitions_) level.

```sh
smcat --direction left-right \
  --dot-graph-attrs "bgcolor=dodgerblue color=white fontname=courier fontcolor=white" \
  --dot-node-attrs "color=white fontname=courier fontcolor=white" \
  --dot-edge-attrs "color=white fontname=courier fontcolor=white" \
  docs/samples/cassetteplayer.smcat
```

#### Using the API

```javascript
const smcat = require("state-machine-cat");
...
const lDotGraphAttrs = [
  { name: "bgcolor", value: "dodgerblue" },
  { name: "color", value: "white" },
  { name: "fontname", value: "courier" },
  { name: "fontcolor", value: "white" }
];
const lDotNodeAttrs = [
  { name: "color", value: "white" },
  { name: "fontname", value: "courier" },
  { name: "fontcolor", value: "white" }
];
const lDotEdgeAttrs = [
  { name: "color", value: "white" },
  { name: "fontname", value: "courier" },
  { name: "fontcolor", value: "white" }
];
const lSVG = smcat.render(yourGraphSource, {
  inputType: "smcat",
  outputType: "svg",
  dotGraphAttrs: lDotGraphAttrs,
  dotNodeAttrs: lDotNodeAttrs,
  dotEdgeAttrs: lDotEdgeAttrs
});
...
```

#### Using the online interpreter

The attribute-pass-through is available in the online interpreter through query parameters.

#### Appendix: styling with graphviz

GraphViz has three general levels for styling the whole _graph_ (our state machine), _node_ (our _states_) end _edge_ (_transitions_). Each of them take their own attributes. 

For our example we'll take the graphviz dot program state-machine-cat generated for our
cassetteplayer:

<details>
<summary>casssetteplayer.dot</summary>

```graphviz
digraph "state transitions" {
  fontname="Helvetica" fontsize=12 penwidth=2.0 splines=true ordering=out compound=true overlap=scale nodesep=0.3 ranksep=0.1 rankdir=LR
  node [shape=plaintext style=filled fillcolor=transparent fontname=Helvetica fontsize=12 penwidth=2.0]
  edge [fontname=Helvetica fontsize=10]

    "initial" [shape=circle style=filled fillcolor=black fixedsize=true height=0.15 label=""]
    "off" [margin=0 label= < 
      <table align="center" cellborder="0" border="2" style="rounded" width="48">
        <tr><td width="48" cellpadding="7">off</td></tr>
      </table>
    >]
    subgraph "cluster_on" {
      label= <
      <table cellborder="0" border="0">
        <tr><td>on</td></tr>
      </table>
      > style=rounded penwidth=2.0
      "on" [shape=point style=invis margin=0 width=0 height=0 fixedsize=true]
        "stopped" [margin=0 label= < 
      <table align="center" cellborder="0" border="2" style="rounded" width="48">
        <tr><td width="48" cellpadding="7">stopped</td></tr>
      </table>
    >]
    "playing" [margin=0 label= < 
      <table align="center" cellborder="0" border="2" style="rounded" width="48">
        <tr><td width="48" cellpadding="7">playing</td></tr>
      </table>
    >]
    "paused" [margin=0 label= < 
      <table align="center" cellborder="0" border="2" style="rounded" width="48">
        <tr><td width="48" cellpadding="7">paused</td></tr>
      </table>
    >]
  
    }

    "initial" -> "off" [label=" "]
    "off" -> "stopped" [label="power   \l"]
    "on" -> "off" [label="power   \l" ltail="cluster_on"]
    "stopped" -> "playing" [label="play   \l"]
    "playing" -> "stopped" [label="stop   \l"]
    "playing" -> "paused" [label="pause   \l"]
    "paused" -> "playing" [label="pause   \l"]
    "paused" -> "stopped" [label="stop   \l"]
}
```

</details>

If you study it closer you'll see the first three lines look like this (comments added for clarity):
```graphviz
// graph level attributes
fontname="Helvetica" fontsize=12 penwidth=2.0 splines=true ordering=out compound=true overlap=scale nodesep=0.3 ranksep=0.1 rankdir=LR

// node level attributes
node [shape=plaintext style=filled fillcolor=transparent fontname=Helvetica fontsize=12 penwidth=2.0]

// edge level attributes
edge [fontname=Helvetica fontsize=10]
```

We're going to modify the general styling by adding attributes to these three lines

##### Styling the graph

We'd like the graph to have a blue background and a fixed-width font. `dodgerblue`
seems nice, and courier has a nice oldskool vibe to it, so we'll go for that:

```graphviz
bgcolor=dodgerblue // defines the background color of the whole graph
color=white        // anything not a node (state) or edge (transition) or text gets this color
fontcolor=white    // to color graph level text
fontname=courier   // sets the font of graph level text
```

As you see, this is a step in the right direction, but it does not style
any of the nodes (except parts of composite ones) nor any of the edges.
So we'll need to repeat this for nodes and edges as well.

![cassetteplayer-graph-white](https://user-images.githubusercontent.com/4822597/63228599-986ded00-c1f5-11e9-8ca7-a6dd6c4e9f04.png)

##### Styling nodes and edges

As most of our nodes and edges use 'transparent' as background ('fill') color, there
is no need to specify that (nor is it possible - on node level something 
akin to the bgcolor attribute is called fillcolor). The rest of the attributes
we can just reuse

```graphviz
color=white        // give node lines this color
fontcolor=white    // give text in and on nodes this color
fontname=courier   // use this font
```

The graph now looks like this:
![cassetteplayer-node-white](https://user-images.githubusercontent.com/4822597/63228603-a885cc80-c1f5-11e9-82f0-d943d7e07c9f.png)


Repeating the same for the edges, gives us the final result:

![cassetteplayer-styled](https://user-images.githubusercontent.com/4822597/63228623-e5ea5a00-c1f5-11e9-95f3-724f0a8acda4.png)

<details>
<summary>cassetteplayer-styled.dot</summary>

```graphviz
digraph "state transitions" {
  fontname="Helvetica" fontsize=12 penwidth=2.0 splines=true ordering=out compound=true overlap=scale nodesep=0.3 ranksep=0.1 rankdir=LR bgcolor=dodgerblue color=white fontname=courier fontcolor=white
  node [shape=plaintext style=filled fillcolor=transparent fontname=Helvetica fontsize=12 penwidth=2.0 color=white fontname=courier fontcolor=white]
  edge [fontname=Helvetica fontsize=10 color=white fontname=courier fontcolor=white]

    "initial" [shape=circle style=filled fillcolor=black fixedsize=true height=0.15 label=""]
    "off" [margin=0 label= < 
      <table align="center" cellborder="0" border="2" style="rounded" width="48">
        <tr><td width="48" cellpadding="7">off</td></tr>
      </table>
    >]
    subgraph "cluster_on" {
      label= <
      <table cellborder="0" border="0">
        <tr><td>on</td></tr>
      </table>
      > style=rounded penwidth=2.0
      "on" [shape=point style=invis margin=0 width=0 height=0 fixedsize=true]
        "stopped" [margin=0 label= < 
      <table align="center" cellborder="0" border="2" style="rounded" width="48">
        <tr><td width="48" cellpadding="7">stopped</td></tr>
      </table>
    >]
    "playing" [margin=0 label= < 
      <table align="center" cellborder="0" border="2" style="rounded" width="48">
        <tr><td width="48" cellpadding="7">playing</td></tr>
      </table>
    >]
    "paused" [margin=0 label= < 
      <table align="center" cellborder="0" border="2" style="rounded" width="48">
        <tr><td width="48" cellpadding="7">paused</td></tr>
      </table>
    >]
  
    }

    "initial" -> "off" [label=" "]
    "off" -> "stopped" [label="power   \l"]
    "on" -> "off" [label="power   \l" ltail="cluster_on"]
    "stopped" -> "playing" [label="play   \l"]
    "playing" -> "stopped" [label="stop   \l"]
    "playing" -> "paused" [label="pause   \l"]
    "paused" -> "playing" [label="pause   \l"]
    "paused" -> "stopped" [label="stop   \l"]
}
```

</details>

**Comment by Jiajun-Deng** [comment]
Thanks! It helps a lot!
While sometimes the graph is not shown completely.
![Screen Shot 2019-08-19 at 3 46 47 PM](https://user-images.githubusercontent.com/46533014/63304388-72edeb80-c2a8-11e9-9a22-8089f38a8b83.png)
It has nothing to do with the styling. Before I tried to style the svg sometimes it shows like this way. I've checked the svg code, the node text has been in the correct position. Also when I hover on the node, the text is shown correctly. I have no idea what's wrong with the graph. Have you ever run into this situation?

**Comment by sverweij** [comment]
Not experienced before. This can happen. though, when there's css either in the svg itself or in the the page in which it is embedded that influences the classes within the generated svg - could you check that?

 i.e. `.node { stroke: white }` in a `<style>` tag on html level (i.e. in the head) will make everything in the svg `<g>`'s with class `node` get a white stroke - which makes letters white against a white background.  `.node path {fill: white}` will have a similar effect.

**Comment by Jiajun-Deng** [comment]
I've checked the html page but found nothing like that.
Below is the generated svg code, seems correct.
After refreshing the page, everything will be fine again.
![Screen Shot 2019-08-20 at 3 12 21 PM](https://user-images.githubusercontent.com/46533014/63380863-07198a80-c35d-11e9-963d-d120f34f493c.png)

**Comment by Jiajun-Deng** [comment]
I've checked the style files in chorme.

> This is when I block the g.node styling. The text will show correctly.

![Screen Shot 2019-08-20 at 3 24 40 PM](https://user-images.githubusercontent.com/46533014/63381856-29140c80-c35f-11e9-8644-de9ded781eb8.png)
![Screen Shot 2019-08-20 at 3 24 48 PM](https://user-images.githubusercontent.com/46533014/63381857-29140c80-c35f-11e9-9127-3cb8e1ab258f.png)

> This is the css code shown in chrome inspector. As it it. I understand now how it affects the text.

![Screen Shot 2019-08-20 at 3 24 59 PM](https://user-images.githubusercontent.com/46533014/63381858-29140c80-c35f-11e9-8034-bb877a12cfb6.png)
![Screen Shot 2019-08-20 at 3 25 04 PM](https://user-images.githubusercontent.com/46533014/63381859-29140c80-c35f-11e9-9ed3-d11f797f2c48.png)

> The fill color is shown below the node background.  I do have another plugin installed and it has a file called diagram.scss. The styling has been affected by it I'm sure.

![Screen Shot 2019-08-20 at 3 27 10 PM](https://user-images.githubusercontent.com/46533014/63381860-29140c80-c35f-11e9-9ffd-28e2904d293f.png)

**Comment by Jiajun-Deng** [comment]
I guess the best way to avoid this is to write my own css. I don't have one right now.
